source "https://rubygems.org"
gem 'sinatra', '~>1.4.0'
gem 'sinatra-contrib'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'thin'
gem 'haml'
gem 'barista'
gem 'mongo'
gem 'bson_ext'
gem 'mongo_mapper'
